from .TestLabelCreateView import TestLabelCreateView
from .TestLabelDeleteView import TestLabelDeleteView
from .TestLabelDetailView import TestLabelDetailView
from .TestLabelExportFormView import TestLabelExportFormView
from .TestLabelUpdateView import TestLabelUpdateView
from .TestLabelExportDownloadView import TestLabelExportDownloadView