# Generated by Django 4.1.3 on 2022-12-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('admission_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('expiration_date_optional', models.TextField()),
                ('test_end_date', models.DateField()),
                ('sample_size', models.CharField(max_length=32)),
                ('appeal_test', models.BooleanField()),
                ('control_type', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore')], default='FR', max_length=3)),
                ('sample_type', models.CharField(choices=[('XD', 'Przetwory')], default='XD', max_length=3)),
                ('source_place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='webapp.testingfacility')),
            ],
        ),
    ]
