# Generated by Django 4.1.3 on 2022-12-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsample',
            old_name='source_place',
            new_name='source_facility',
        ),
        migrations.AddField(
            model_name='testsample',
            name='customer_name',
            field=models.CharField(default='xd', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsample',
            name='control_type',
            field=models.CharField(default='Bez zastrzezen', max_length=128),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='sample_type',
            field=models.CharField(choices=[('T1', 'Type 1'), ('T2', 'Type 2')], default='T2', max_length=3),
        ),
        migrations.CreateModel(
            name='TestLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('parameter_name', models.CharField(max_length=128)),
                ('labeling', models.CharField(max_length=128)),
                ('specification', models.CharField(max_length=128)),
                ('law', models.CharField(max_length=128)),
                ('sample_amount', models.IntegerField(max_length=128)),
                ('test_result', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('method_status', models.CharField(max_length=128)),
                ('margin', models.CharField(max_length=128)),
                ('test_sample', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='webapp.testsample')),
            ],
        ),
    ]
