# Generated by Django 4.1.3 on 2022-12-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_source_place_testsample_source_facility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlabel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='labeling',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='law',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='method_status',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='sample_amount',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='testlabel',
            name='test_result',
        ),
    ]
