# Generated by Django 4.1.3 on 2023-01-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_testlabel_end_date_remove_testlabel_labeling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingfacility',
            name='place_code',
        ),
        migrations.AddField(
            model_name='testingfacility',
            name='address',
            field=models.CharField(default='Kraków, Papierowa 30', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingfacility',
            name='name',
            field=models.CharField(default='WIJHARS', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testlabel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
