# Generated by Django 4.1.3 on 2023-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_testingfacility_place_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsample',
            name='control_type',
        ),
        migrations.AddField(
            model_name='testsample',
            name='sample_condition',
            field=models.CharField(default='Bez zastrzezeń', max_length=128),
        ),
        migrations.AddField(
            model_name='testsample',
            name='sample_method',
            field=models.CharField(choices=[('T1', 'Type 1'), ('T2', 'Type 2')], default='T2', max_length=128),
        ),
    ]
