# Generated by Django 4.1.3 on 2023-01-14 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_done_testlabel_is_done_testlabel_lod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsample',
            options={'get_latest_by': ['created_at'], 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='testsample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testlabel',
            name='test_sample',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.testsample'),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='expiration_date_optional',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
