# Generated by Django 4.1.3 on 2023-01-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_modelwithtimestamp_reportauthor_testsamplereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelWithTimestamp',
        ),
    ]
