# Generated by Django 4.1.3 on 2023-01-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_delete_modelwithtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsamplereport',
            name='order_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='testsamplereport',
            name='author',
        ),
        migrations.AlterField(
            model_name='testsamplereport',
            name='test_sample',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='webapp.testsample'),
        ),
        migrations.AddField(
            model_name='testsamplereport',
            name='author',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
