# Generated by Django 4.1.3 on 2023-01-15 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_testsamplereport_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsamplereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsamplereport',
            name='test_sample',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='webapp.testsample'),
        ),
    ]
