# Generated by Django 4.1.3 on 2023-01-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_testsamplereport_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsamplereport',
            old_name='order_id',
            new_name='contract_id',
        ),
    ]
