# Generated by Django 4.1.3 on 2023-01-16 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_order_id_testsamplereport_contract_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportAuthor',
        ),
        migrations.AddField(
            model_name='testlabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
