# Generated by Django 4.1.3 on 2023-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_delete_reportauthor_testlabel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testlabel',
            old_name='margin',
            new_name='uncertainty',
        ),
        migrations.AddField(
            model_name='testlabel',
            name='label_type',
            field=models.CharField(choices=[('FC', 'Fizykochemiczne'), ('OG', 'Organoleptyczne')], default='FC', max_length=10),
            preserve_default=False,
        ),
    ]
