# Generated by Django 4.1.3 on 2023-01-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rename_margin_testlabel_uncertainty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testlabel',
            old_name='label_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='testsample',
            old_name='sample_type',
            new_name='type',
        ),
    ]
