# Generated by Django 4.1.3 on 2023-01-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_rename_label_type_testlabel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlabel',
            name='value',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
