# Generated by Django 4.1.3 on 2023-01-31 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_testlabel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsample',
            name='admission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='test_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
