# Generated by Django 4.1.3 on 2023-01-31 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_testsample_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlabel',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='testlabel',
            name='labeling',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testlabel',
            name='regulation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testlabel',
            name='specification',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testlabel',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='testlabel',
            constraint=models.CheckConstraint(check=models.Q(('specification__isnull', False), ('labeling__isnull', False), ('regulation__isnull', False), _connector='OR'), name='one_of_three_required'),
        ),
    ]
