from .HomeView import HomeView
from .TestLabelCreateView import TestLabelCreateView
from .TestSampleCreateView import TestSampleCreateView
from .TestSampleDetailView import TestSampleDetailView
from .TestSampleListView import TestSampleListView
from .TestLabelDetailView import TestLabelDetailView
from .TestLabelUpdateView import TestLabelUpdateView
